### ISSUE TITLE
Suggestions or explanation 

### ISSUE THREAD

**Issue by zezo357** [seel-channel/video_viewer#1]
I have in my class the size of the video i would love to add it in the quality picking UI

and how can I force landscape mode in full screen

thanks in advance.

**Comment by seel-channel** [comment]
1. Tu puedes cambiar el tamaño del video o el texto que aparecerá en la Quality Picking UI. Por ejemplo

``` dart
VideoViewer(
  source: {
    "Batman": VideoSource.network("https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4"),
    "1080 x 1920": VideoSource.network("http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"),
  }
);
```

No hay manera de forzar el modo landscape, lo agregaré en futuras actualizaciones.

**Comment by zezo357** [comment]
oh I will be waiting for those updates ♥

**Comment by seel-channel** [comment]
In version **1.0.2** you can enter the argument **onFullscreenFixLandscape: true** to open the full screen. This can only be in landscape mode
