### ISSUE TITLE
I found some minor issues with your package

### ISSUE THREAD

**Issue by MeTubeapp** [seel-channel/video_viewer#13]
1-When we press full screen button it gives a exception error the getter size was called null.
2-thumbnail does not show . I don't know why its show only white colour.
3-full screen have a some issues like its does not go back normal i mean in potrait mode from landscape mode.
4-http url doesn't work properly.

Please resolve as soon as possible i love this package 😉

**Comment by seel-channel** [comment]
I don't have computer XD. I will solved it as soon as possible uwu

**Comment by MeTubeapp** [comment]
Bro please fixed soon i m waiting for next update 😃.

**Comment by seel-channel** [comment]
I can't :(. My computer is broken, but in little days I get one and I will fix these issues

**Comment by seel-channel** [comment]
I just fixed all. Try version 1.1.0
