### ISSUE TITLE
Dudas y problemas sobre el plugin

### ISSUE THREAD

**Issue by alurei97** [seel-channel/video_viewer#14]
Primero de todo, gracias por el plugin, lo acabas de publicar y tiene casi todo lo que necesitaba para mi app: thumbnail, subtítulos, varias calidades... Incluso, tras investigar el código, he encontrado que puedo personalizar los subtítulos. 

Antes de incluirlo en mi app, he estado probando con el ejemplo, en mi código tengo:
```
...
   VideoViewer(
      source: {
        "SD": VideoSource(
          video: VideoPlayerController.network("<url vídeo_sd>"),
          subtitle: {
            "English": VideoViewerSubtitle.network(
              "<url eng.srt>",
              type: SubtitleType.srt,
            ),
            "Español": VideoViewerSubtitle.network(
              "<url spa.srt>",
              type: SubtitleType.srt,
            ),
          },
        ),
        "HD": VideoSource(
          video: VideoPlayerController.network("<url vídeo_hd>"),
          subtitle: {
            "English": VideoViewerSubtitle.network(
              "<url eng.srt>",
              type: SubtitleType.srt,
            ),
            "Español": VideoViewerSubtitle.network(
              "<url spa.srt>",
              type: SubtitleType.srt,
            ),
          },
        ),
      },
      style: VideoViewerStyle(
          thumbnail: Image.network("<url .jpg>"),
          subtitleStyle: SubtitleStyle(
              style: TextStyle(
                fontSize: 14,
                color: Colors.white,
              ),
              alignment: Alignment(-1.0, 1.0),
              padding: const EdgeInsets.only(left: 50, right: 40, bottom: 40))),
    );
...
```

1. Como ya han dicho en otro issue ("full screen have a some issues like its does not go back normal i mean in potrait mode from landscape mode.") cuando salgo de la pantalla completa, a veces se queda el fondo negro como si no saliera de la pantalla completa.

2. Cuando he dejado que cargue bien la calidad SD y cambio a HD, primero tarda un poco en cambiar, y cuando cambia, se ve el vídeo HD pero se sigue escuchando la calidad SD sin posibilidad de pausarlo ni nada, y se siguen viendo los subtítulos del SD hasta que salen los nuevos de la versión HD.

3. `SubtitleStyle` no se aplica cuando está en horizontal, pero sí que funciona en modo vertical/portrait.

4. ¿Cómo puedo hacer que por defecto no cargue ningún subtítulo? Ahora mismo carga directamente los subtítulos en inglés (creo que porque son los primeros de la lista).

**Comment by seel-channel** [comment]
1. Realmente el Fullscreen funciona mal. Lo que hace es un Navigator.pop(context) y eso provoca ese problema.

2. Eso es provoca ya que espera a que se inicialice el controlador para despues cambiarlo. En la siguiente update voy a quitar eso y directamente se cierre el SettingMenu.
 
3. Utilizo una forma de crear un sistema de Responsive en el Fullscreen pero funciona mal, por eso mismo la siguiente update voy a eliminar el responsive y asi se eliminara ese problema.

4. Inicialmente no habia pensando en eso, pero voy a agregar la opcion de iniciar el subtitulo en un idioma preferente o que no inicialice ningún idioma

**Comment by alurei97** [comment]
Gracias por la respuesta, espero impaciente la siguiente update.

**Comment by seel-channel** [comment]
Todo arreglado baby. Acabo de lanzar la 1.1.0

**Comment by alurei97** [comment]
Oh yeah baby! Mañana lo pruebo, pero confío que va a funcionar perfectamente jaja

**Comment by seel-channel** [comment]
JAJAJAJA

**Comment by alurei97** [comment]
Ahora funciona bien la pantalla completa y los subtítulos, pero sigue estando el problema de las calidades (el 2.).

**Comment by seel-channel** [comment]
Al cambiar la calidad  se tiene que inicializar el nuevo video-controlador (por eso tarda) y una vez que se inicializa se cambia el controlador actual por el nuevo. Según yo, no es posible que se siga escuchando el audio anterior (antes sucedía eso, pero al empezar a utilizar **Provider** (Administrador de estado) ese problema no lo he vuelto a ver). Pero probablemente no termine de entender tu issue, si pudieras enviarme un vídeo o alguna screenshot lo agradecería bastante.

**Comment by alurei97** [comment]
· Android: te paso [este vídeo](https://ucordoba-my.sharepoint.com/:v:/g/personal/i52lurea_uco_es/EdHVuWIQARBJmw9wtUbkx7oBRdGqsGjfYzpGu0hITdKjdQ?e=zFNLOt) que acabo de grabar (es un poco complicado de apreciar por las bandas negras, pero fíjate en la etiqueta de DEBUG para saber si el móvil está en vertical u horizontal): cuando cambio de calidad pasan unos segundos (normal, por ser un vídeo tan largo) y luego la imagen y los subs se quedan fijos hasta que "refresco" la imagen, ya sea moviendo el móvil a vertical y volviendo a horizontal (minuto 0:37) o adelantando 10 segundos (minuto 1:25).

· iOS: no he vuelto a probar, pero ayer, antes de enviarte mi mensaje anterior, pasa como en Android pero el vídeo de la calidad anterior seguía sonando a la vez que el audio de la calidad actual.

**Comment by seel-channel** [comment]
Pasame el codigo de tu app en Android porque la neta eso es algo grave para probarlo en mi dispositivo y arreglarlo.

**Comment by alurei97** [comment]
Iba a hacerte una versión reducida de mi app con solo la actividad/pantalla en la que tengo el reproductor, pero es que simplemente creando un nuevo proyecto y añadiendo el plugin y un `VideoSource` ya falla como te he enseñado en el vídeo anterior.

[Código de ejemplo](https://ucordoba-my.sharepoint.com/:u:/g/personal/i52lurea_uco_es/EVgwo2snk8NIoIuAihYtS_kB7aUjD3OvuhFI9NwMq_qonA?e=xFmSMo) (Solo lo he configurado para Android)

**Comment by seel-channel** [comment]
Ya quedó otra vez baby :)

**Comment by alurei97** [comment]
Se me olvidó avisar que ya funciona perfectamente <3

**Comment by seel-channel** [comment]
Pues ni tanto, encontre otros bugs; pero luego los soluciono
