### ISSUE TITLE
something go wrong with dispose in update .

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#15]
if the user enter video and does not wait to begin  ,and pop up .
_controller.dispose();  , _controller.controller.dispose();   do not work 
and the video will start in the background , and does not close until the user close the app .

**Comment by seel-channel** [comment]
I will try to fix that in the next update

**Comment by seel-channel** [comment]
I just release version 1.0.1. Can you try again and tell me what happened?
