### ISSUE TITLE
progress bar go wrong in fullscreen bar in rtl language as ARABIC

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#16]
if can set Directionality or some thing to fix that ,
thanks bro .

**Comment by seel-channel** [comment]
Can you send me a screenshot? uwu

**Comment by seel-channel** [comment]
The ProgressBarTextPosition follows your finger on dragging

**Comment by Joseph-Nathan** [comment]
![Screenshot_1614804723](https://user-images.githubusercontent.com/60202661/109873758-dd8e2e80-7c76-11eb-8556-0c42c1d2c2b0.png)
![Screenshot_1614804778](https://user-images.githubusercontent.com/60202661/109873781-e41ca600-7c76-11eb-870b-578b77880ca8.png)

**Comment by seel-channel** [comment]
I can't see the problem :( Can you explain me?

**Comment by seel-channel** [comment]
It The problem the White Dot?. In the second image the dot is at the start and the blue bar is in the middle of size

**Comment by Joseph-Nathan** [comment]
progress white circle should be in the end of blue progressBar ,

**Comment by Joseph-Nathan** [comment]
yep

**Comment by seel-channel** [comment]
I will solve that in the next update (15 days)

**Comment by Joseph-Nathan** [comment]
OK thank bro .

**Comment by seel-channel** [comment]
I think the problem is solved at release 1.2.0
