### ISSUE TITLE
Migrate Package To Null Safety

### ISSUE THREAD

**Issue by RounakTadvi** [seel-channel/video_viewer#17]
Hey, I love this package, I would really love it if you might be able to migrate to null safety.

**Comment by seel-channel** [comment]
In a near future a will create the null safety version

**Comment by RounakTadvi** [comment]
Hey, is it fine if i created a PR to help contribute to your package by migrating it to Sound Null Safety?

**Comment by seel-channel** [comment]
No problem bro. I'm waiting to universal_html for it create the Null Safety Compatibility, because is the last dependency it need

**Comment by RounakTadvi** [comment]
Hey, turns out universal_html is compatible now, i hope we'll get a null-safe version soon

**Comment by seel-channel** [comment]
Yes. I'm developing the new update now.

**Comment by RounakTadvi** [comment]
Any way, i can help speed things up?

**Comment by seel-channel** [comment]
Done! (1.2.0 release)
