### ISSUE TITLE
failed to build IOS ,method 'GetMedia' isn't defined

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#18]
Showing Recent Messages
../../src/flutter/.pub-cache/hosted/pub.dartlang.org/video_viewer-1.0.9+1/lib/ui/video_core/video_core.dart:219:18: Error: The method 'GetMedia' isn't defined for the class '_VideoViewerCoreState'.

Showing Recent Messages
 - '_VideoViewerCoreState' is from 'package:video_viewer/ui/video_core/video_core.dart' ('../../src/flutter/.pub-cache/hosted/pub.dartlang.org/video_viewer-1.0.9+1/lib/ui/video_core/video_core.dart').

Showing Recent Messages
Try correcting the name to the name of an existing method, or defining a method named 'GetMedia'.

Showing Recent Messages
    final size = GetMedia(context).size;

Showing Recent Messages
../../src/flutter/.pub-cache/hosted/pub.dartlang.org/video_viewer-1.0.9+1/lib/ui/video_core/widgets/forward_and_rewind/layout.dart:18:23: Error: The method 'GetMedia' isn't defined for the class 'RewindAndForwardLayout'.

Showing Recent Messages
 - 'RewindAndForwardLayout' is from 'package:video_viewer/ui/video_core/widgets/forward_and_rewind/layout.dart' ('../../src/flutter/.pub-cache/hosted/pub.dartlang.org/video_viewer-1.0.9+1/lib/ui/video_core/widgets/forward_and_rewind/layout.dart').

Showing Recent Messages
Try correcting the name to the name of an existing method, or defining a method named 'GetMedia'.

Showing Recent Messages
      SizedBox(width: GetMedia(context).width / 2),

Showing Recent Messages
../../src/flutter/.pub-cache/hosted/pub.dartlang.org/video_viewer-1.0.9+1/lib/ui/overlay/widgets/progress_bar.dart:81:42: Error: The argument type 'BuildContext' can't be assigned to the parameter type 'double'.

Showing Recent Messages
../../src/flutter/.pub-cache/hosted/pub.dartlang.org/video_viewer-1.0.9+1/lib/ui/overlay/widgets/progress_bar.dart:81:42: Error: The argument type 'BuildContext' can't be assigned to the parameter type 'double'.

Showing Recent Messages
      builder: (value) => _dot(maxWidth, value, 2),

Showing Recent Messages
../../src/flutter/.pub-cache/hosted/pub.dartlang.org/video_viewer-1.0.9+1/lib/ui/overlay/widgets/progress_bar.dart:81:16: Error: The argument type 'Widget Function(BuildContext)' can't be assigned to the parameter type 'Widget Function(BuildContext, double, Widget)'.

Showing Recent Messages
 - 'Widget' is from 'package:flutter/src/widgets/framework.dart' ('../../src/flutter/packages/flutter/lib/src/widgets/framework.dart').

Showing Recent Messages
 - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../src/flutter/packages/flutter/lib/src/widgets/framework.dart').

Showing Recent Messages
      builder: (value) => _dot(maxWidth, value, 2),

can you help me , i do not know where the proplem .

**Comment by seel-channel** [comment]
HAHAHAHA I UPDATED MY HELPERS PACKAGE AND GETMEDIA IS DELETED AND REPLACED BY BUILDMEDIA

**Comment by seel-channel** [comment]
I Just solved this Issue at Release 1.1.0
