### ISSUE TITLE
in next update can you support dio ^4.0.0-beta5

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#19]
Because no versions of video_viewer match >1.1.0 <2.0.0 and video_viewer 1.1.0 depends on dio ^3.0.10, video_viewer ^1.1.0 requires dio ^3.0.10.
And because no versions of dio match >3.0.10 <4.0.0, video_viewer ^1.1.0 requires dio 3.0.10.
And because dio 3.0.10 depends on http_parser >=0.0.1 <4.0.0 and http >=0.13.0 depends on http_parser ^4.0.0, video_viewer ^1.1.0 is incompatible with http >=0.13.0.
And because firebase_storage >=8.0.0 depends on firebase_storage_web ^1.0.0 which depends on http ^0.13.0, video_viewer ^1.1.0 is incompatible with firebase_storage >=8.0.0.
So, because eteaching depends on both video_viewer ^1.1.0 and firebase_storage ^8.0.0, version solving failed.

**Comment by seel-channel** [comment]
Done! (1.2.0 release)
