### ISSUE TITLE
Allow HTTP Headers

### ISSUE THREAD

**Issue by jinyus** [seel-channel/video_viewer#2]
Hello, could you possibly add support for http header?

**Comment by seel-channel** [comment]
I think you can do an `http.get(URL, headers: ...)`, after creating a VideoPlayerController.network(URL) and assign it.

NOTE: I don't know too much about HTTP methods

**Comment by seel-channel** [comment]
Done! At release 1.2.1 the `VideoPlayerController.network` allows use `httpHeaders`
