### ISSUE TITLE
In the full screen mode, if you change the video link, the video screen is not updated

### ISSUE THREAD

**Issue by msterzhang** [seel-channel/video_viewer#21]
Thank you for your work！

Android
version:1.1.0
flutter:2.0.2

In the full screen mode, if you change the video link, the video screen is not updated, but the sound and so on are updated.

**Comment by msterzhang** [comment]
bug video

https://user-images.githubusercontent.com/31364579/111279954-38ac2200-8676-11eb-861e-659de0f1d466.mp4

**Comment by seel-channel** [comment]
Can you send me your code? For solve this issue

**Comment by msterzhang** [comment]
ok!
[test code.zip](https://github.com/seel-channel/video_viewer/files/6153041/test.code.zip)

**Comment by alurei97** [comment]
I have this problem too (#14, sorry it's in spanish). 
It works again if you "update the image": exit and reenter fullscreen, move the phone to horizontal or vertical, or go forward or backward some seconds.

**Comment by seel-channel** [comment]
Done! (1.2.0 release)
