### ISSUE TITLE
Subs no desaparecen hasta que sale los siguientes

### ISSUE THREAD

**Issue by alurei97** [seel-channel/video_viewer#22]
Buenas, he detectado otro problema y es que, cuando los subs están activados, sale el texto que corresponde, pero no desaparecen, se mantienen hasta que sale la siguiente línea de texto en vez de borrarse cuando debería.

_Uso un fichero .srt, no sé si solo pasa con este tipo de subs o si con el código de ejemplo del repo también pasa. Cuando pueda lo pruebo._

**Comment by seel-channel** [comment]
Listo en la version 1.2.0
