### ISSUE TITLE
¿Es posible reproducir un vídeo desde X segundos hasta Y segundos?

### ISSUE THREAD

**Issue by alurei97** [seel-channel/video_viewer#27]
Buenas de nuevo, aún sigo usando tu plugin, pero ahora tengo un nuevo problema.
Desde la app de Flutter obtengo el vídeo desde un PHP y funciona bien, pero ahora quiero que el vídeo se reproduzca, por ejemplo desde 0:00 - 2:00 y en otra vista desde 2:00 - 4:00, etc... 

Mi pregunta es si se podría elegir desde Dart desde dónde hasta dónde quiero que se reproduzca el vídeo completo, así no tendría que editarlo manualmente y subir todos esos cortes al servidor, y me serviría el mismo código por si esa duración cambia de nuevo en el futuro.

Un saludo.

**Comment by seel-channel** [comment]
No hay forma nativa, pero creo que puedes hacer un truquillo. Con el controller.video agregar un listener y hacer un rango de tiempo. Que cuando avance más de 4 min te regresa al 2 min o cuando sea menor al 2 de regrese al 2min

**Comment by alurei97** [comment]
He visto esto que podría servirme:
Con `controller.video.position` puedo saber el segundo actual por el que va el vídeo.
Con `controller.video.seekTo()` puedo saltar a dónde quiera
Y luego `controller.video.setLooping()` podría servirme también.

Pruebo y te cuento.

**Comment by seel-channel** [comment]
> He visto esto que podría servirme:
> Con `controller.video.position` puedo saber el segundo actual por el que va el vídeo.
> Con `controller.video.seekTo()` puedo saltar a dónde quiera
> Y luego `controller.video.setLooping()` podría servirme también.
> 
> Pruebo y te cuento.

Así es, y para que te notifiqué el cambio de posición le agregar un listener que evalúe la condición (controller.video.addListener())

**Comment by alurei97** [comment]
Perdón por no contestar antes pero no he podido probarlo hasta hoy, he probado lo que me comentaste pero no me funciona:
![image](https://user-images.githubusercontent.com/23730052/122640132-0b9c5f00-d0fe-11eb-86e2-2ac4de85271e.png)

Eso es porque `position` es `Future<Duration>`, pero si pongo `Future<Duration> == ` no puedo añadir `(seconds: 120)`... ¿se te ocurre alguna solución?

**Comment by alurei97** [comment]
He estado probando cosas pero no me funciona nada, ¿se te ocurre alguna otra forma para poder comparar la duración actual del vídeo con la que yo diga?

**Comment by seel-channel** [comment]
Listo mi pana. Con esto cortaras los videos y solo se mostrara el contenido del segundo 0 al segundo 120

VideoViewer(source: {
      "Movie: VideoSource(
        video: VideoPlayerController.network(
          "https://felipemurguia.com/assets/videos/mortal_machines_trailer.mp4",
        ),
        range: Tween<Duration>(
          begin: Duration.zero,
          end: const Duration(seconds: 120),
        ),
      ),
    }
);

**Comment by alurei97** [comment]
Gracias de nuevo!!!! <3 En cuanto pueda lo pruebo
