### ISSUE TITLE
Unable to play m3u8 links on iOS devices 

### ISSUE THREAD

**Issue by wilz05** [seel-channel/video_viewer#29]
Thank you for the awesome product. 

I have noticed some of the links are not working on iOS devices as well as iOS simulators. based on your example m3u8 link 
https://sfux-ext.sfux.info/hls/chapter/105/1588724110/1588724110.m3u8 it works well on both devices.

I have tried some m3u8 links which are not working on iOS real devices and simulators but works on android devices, please find the below example links.

https://5421175365ea3.streamlock.net/live/smil:switch.smil/playlist.m3u8
https://dcunilive28-lh.akamaihd.net/i/dclive_1@533583/master.m3u8

Is there anyway we can fix them ?

**Comment by seel-channel** [comment]
Can you try the new `video_viewer: ^1.2.4`. I fixed a few HLS bugs, probably now you can use them in iOS

**Comment by wilz05** [comment]
Thank you so much for the above fix,  indeed it works on iOS but stopped  working on android, if the stream takes sometime to load it just gives play back error.
