### ISSUE TITLE
Support Widget header 

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#3]
Support Widget header  ,
forward does not appear and does not work ,
can support hls format quality ,
can support one controller for two dataSource one for video and one for audio ,
or Muti for audio ,
thanks for your player ,

**Comment by seel-channel** [comment]
I added the Widget Header and fixed the double-tap-forward

**Comment by seel-channel** [comment]
VideoPlayer isn't had multi-audio support. I thought of a solution but is not pretty.

**Comment by Joseph-Nathan** [comment]
we can two controller ;
VideoPlayerController  _controller = VideoPlayerController.network( otherAudioURL , 
videoPlayerOptions: VideoPlayerOptions(mixWithOthers: true , ) );
to work audio on other controller but i can not link theme ,
thanks for your response .

**Comment by seel-channel** [comment]
Added HSL format support an MixWithOthers on the release 1.0.5
