### ISSUE TITLE
Turn off brightness control

### ISSUE THREAD

**Issue by VictorLekweuwa** [seel-channel/video_viewer#32]
Is there a way to turn off brightness control from gesture detector on the video? I don't want my users changing there brightness settings when trying to scroll down on touching the video.

**Comment by VictorLekweuwa** [comment]
I literally commented on the wrong library repository. Sorry.

**Comment by seel-channel** [comment]
> I literally commented on the wrong library repository. Sorry.

HAHAHAH

**Comment by zezo357** [comment]
i am interested to know the package can i know its name?

**Comment by seel-channel** [comment]
I'm going to add this feature in the next update (I don't know when the next version will be released lol)

**Comment by seel-channel** [comment]
> i am interested to know the package can i know its name?

X2
