### ISSUE TITLE
iOS App Crash on Startup

### ISSUE THREAD

**Issue by RounakTadvi** [seel-channel/video_viewer#36]
I'm using the latest version of video_viewer package , the iOS app crashes when i try to run it on a simulator or a real iPhone device. @FelipeMurguia Kindly, look into it.

**Comment by RounakTadvi** [comment]
Never mind fixed it I replaced the cached_video_player package with video_player package and everything is working appropriately and the crash issue is fixed

**Comment by seel-channel** [comment]
Thanks for the information

**Comment by seel-channel** [comment]
I've just migrate to video_player package, the new `video_viewer: ^1.2.4` no longer use the cache_video_player
