### ISSUE TITLE
Update Provider dependency

### ISSUE THREAD

**Issue by Tom3652** [seel-channel/video_viewer#37]
Hello !

I would like to try your package but i am not able to because i require the ```provider: ^6.0.0``` package and yours is ```provider: ^5.0.0```

Could you please upgrade your dependencies ? 

Thanks in advance

**Comment by seel-channel** [comment]
Ok. I'm going to update it

**Comment by Tamerlanchiques** [comment]
So

**Comment by seel-channel** [comment]
Sorry for the delay. I just updated it
