### ISSUE TITLE
Duration show wrong value

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#4]
I try video with duration 1h 4m 19s,
it appear 01:64:19 on start ,
but after 4m 19s it go well
I think we should 60 m from minute string,
![Screenshot_1608203132](https://user-images.githubusercontent.com/60202661/102480777-74305380-4069-11eb-84dc-2cdc945fcc06.png)
 Double-tapping on the right side of the VideoViewer no thing happen .
thanks for Amazing  Player .

**Comment by seel-channel** [comment]
I fixed both problems on the 1.0.4 release
