### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by hasanm08** [seel-channel/video_viewer#40]
remove` package:path_provider/path_provider.dart` in `lib\domain\entities\video_source.dart`
and use `VideoPlayerController.network` instead of `VideoPlayerController.file`
you can use `https://pub.dev/packages/video_player_web_hls` for hls files

**Comment by seel-channel** [comment]
But I can't use video_player_web_hls in Android and iOS. I said that because I don't know how to force to just use different for different platforms

**Comment by hasanm08** [comment]
[check this](https://stackoverflow.com/questions/58710226/how-to-import-platform-specific-dependency-in-flutter-dart-combine-web-with-an)

**Comment by hasanm08** [comment]
> remove` package:path_provider/path_provider.dart` in `lib\domain\entities\video_source.dart` and use `VideoPlayerController.network` instead of `VideoPlayerController.file` you can use `https://pub.dev/packages/video_player_web_hls` for hls files

you should remove `dart:io` too

**Comment by hasanm08** [comment]
#41 this simple way worked for me but still insist you check [this](https://stackoverflow.com/questions/58710226/how-to-import-platform-specific-dependency-in-flutter-dart-combine-web-with-an) and use it
but if you can't follow those instructions you can build --> test and finally merge my pr

**Comment by seel-channel** [comment]
> #41 this simple way worked for me but still insist you check [this](https://stackoverflow.com/questions/58710226/how-to-import-platform-specific-dependency-in-flutter-dart-combine-web-with-an) and use it
> If you can't follow those instructions you can build --> test and finally merge my pr 

I just merged your pull request
