### ISSUE TITLE
can add Arabic Language 

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#5]
if you time allowed add ar lang in next update ,

it will like thise  

 ///**ARABIC LANGUAGE**
  static const VideoViewerLanguage ar = VideoViewerLanguage(
    settings: "إعدادات",
    quality: "الجودة",
    speed: "السرعة",
    normal : "طبيعي",
  );

**Comment by seel-channel** [comment]
Added the Arabic Language on the release 1.0.5
