### ISSUE TITLE
Support rotation Video

### ISSUE THREAD

**Issue by Joseph-Nathan** [seel-channel/video_viewer#6]
some video take by mobile ,
and in full screen it well be so small 
can we support in settings rotate option :
normal
90°
-90°
180°
thanks pro ,

**Comment by seel-channel** [comment]
Can you send me a screenshot?

**Comment by Joseph-Nathan** [comment]
![Screenshot_1608458203](https://user-images.githubusercontent.com/60202661/102710427-e6e43d80-42ba-11eb-8ce7-5ae469bf726d.png)
this in normal mode ,
![Screenshot_1608458315](https://user-images.githubusercontent.com/60202661/102710462-23179e00-42bb-11eb-96e4-67f4d839e7b4.png)
this in full screen mode ,
in this exp we are luck because video take in vertical mode if video take by phone in horizontal ,
it we be so bad to watch it ,
thanks for Amazing  API .
