### ISSUE TITLE
HLS Streaming not working in iOS

### ISSUE THREAD

**Issue by RounakTadvi** [seel-channel/video_viewer#8]
I'm able to play videos with different resolutions in Android but the video is not playing in iOS.

**Comment by seel-channel** [comment]
I'm sorry, i can't solve that problem because i don't have a Mac computer

**Comment by RounakTadvi** [comment]
Don't worry man,it seems it was a regex error everything is working fine👍 now.Anyways, thanks for the great package you are really doing good community work you should be proud of it!

**Comment by seel-channel** [comment]
Could you send me the solution you used to add it in the next update?

**Comment by RounakTadvi** [comment]
I had an issue with the path of my HLS manifest file on the web, I guess the iOS Native Player verifies the HLS Manifest file by Regular Expression Validation, I fixed the path and the video started playing so if you want to make a change in next update you can just verify the HLS Manifest url path via regex validation and no one will face an issue like this in future. I guess the package named yoyo_player does the same

**Comment by seel-channel** [comment]
I literally stole the HLS code from yoyo_player because I never heard of the HLS video format xd
